name: Update IP List

on:
  schedule:
    - cron: '*/15 * * * *'  # 每 15 分钟运行一次
  workflow_dispatch:        # 手动触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest

    concurrency:
      group: update-ip-list
      cancel-in-progress: true  # 如果有新的工作流运行，取消之前正在运行的

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          fetch-depth: 0  # 确保获取完整的 Git 历史，以便进行 pull 操作

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      # 4. 运行抓取 IP 的脚本（设置超时时间 10 分钟）
      - name: Run script to collect IPs with timeout
        run: |
          timeout 600 python ${{ github.workspace }}/collect_ips.py

      # 5. 配置 Git 用户信息
      - name: Set Git Config
        run: |
          git config --global user.name "${{ secrets.COMMIT_AUTHOR_NAME }}"
          git config --global user.email "${{ secrets.COMMIT_AUTHOR_EMAIL }}"

      # 6. 拉取最新代码并进行 rebase，防止非快进错误
      - name: Pull latest changes
        run: |
          git pull --rebase origin main || true

      # 7. 添加、提交和推送更新
      - name: Commit and push changes
        run: |
          git add ip.txt
          git commit -m "Automatic update" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
