name: CF DNS Collector

on:
  schedule:
    - cron: "*/60 * * * *"      # 每 60 分钟（UTC）
  workflow_dispatch:

permissions:
  contents: write               # 允许提交 ips.txt

# 如果上一次还没结束，取消正在运行的，避免重叠
concurrency:
  group: cf-dns-collector
  cancel-in-progress: true

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 60         # 放宽：脚本低速稳态，运行时间更长

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0        # 保留完整历史，便于 rebase

      - name: Sync with remote (rebase)
        run: |
          git fetch origin ${{ github.ref_name }}
          git pull --rebase origin ${{ github.ref_name }} || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dnspython

      - name: Run collector
        env:
          PYTHONIOENCODING: "utf-8"
          LC_ALL: "C.UTF-8"
          LANG: "C.UTF-8"
        run: |
          python dns_collect.py

      - name: Show IP count
        run: |
          if [ -f ips.txt ]; then
            echo "IPv4 count: $(grep -c '^[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+$' ips.txt || true)"
          else
            echo "ips.txt not found"
          fi

      - name: Commit & Push if ips.txt changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update ips.txt (auto)"
          file_pattern: ips.txt
