# .github/workflows/cf-dns-collector.yml
name: CF DNS Collector

on:
  schedule:
    # GitHub Actions 使用 UTC 时间；*/15 表示每 15 分钟运行一次
    - cron: "*/15 * * * *"
  # 支持手动触发
  workflow_dispatch:

# 允许提交 ips.txt
permissions:
  contents: write

# 防止并发重叠运行
concurrency:
  group: cf-dns-collector
  cancel-in-progress: false

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 1) 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2) 安装 Python（不启用 pip 缓存，也不查找 requirements/pyproject）
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) 安装依赖（显式安装 dnspython）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dnspython

      # 4) 运行采集脚本（如你的文件名不同，请改成对应脚本名）
      - name: Run collector
        env:
          PYTHONIOENCODING: "utf-8"
          LC_ALL: "C.UTF-8"
          LANG: "C.UTF-8"
        run: |
          python dns_collect.py

      # 5) 如 ips.txt 有变化则自动提交
      - name: Commit & Push if ips.txt changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update ips.txt (auto)"
          file_pattern: ips.txt
